#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Usage:  $ sync_extractions_TO_s3 j023507-040202"
    
    exit
fi

root=$1

# Run in root directory, like /Volumes/Pegasus/Grizli/Automatic/

# aws s3 sync --exclude "*" --include "${root}/Extractions/*GrismFLT*"  \
#                           --include "${root}/Extractions/*npy" \
#                           --include "${root}/Extractions/*cat.fits" \
#                           --include "${root}/Extractions/${root}*" \
#                           --follow-symlinks  ./ s3://aws-grivam/Pipeline/

files=`ls *GrismFLT*`
if [[ -z $files ]]; then 
    echo "No files found in $PWD"
    exit
fi

echo "Sync:    `date`" > ${root}.log
aws s3 cp ${root}.log s3://aws-grivam/Pipeline/Log/Sync/

rm ${root}.log

aws s3 sync --exclude "*" --include "*GrismFLT*"  \
                          --include "*npy" \
                          --include "*wcs.fits" \
                          --follow-symlinks ./ s3://aws-grivam/Pipeline/${root}/Extractions

# Public Read on FITS files
aws s3 sync --exclude "*"  --acl public-read --include "${root}*fits" \
                          --include "*cat.fits" \
                          --follow-symlinks ./ s3://aws-grivam/Pipeline/${root}/Extractions

# Public Read on PNG
aws s3 sync --exclude "*" --acl public-read --include "*png"  \
                          --include "*html" \
                          --follow-symlinks ./ s3://aws-grivam/Pipeline/${root}/Extractions
