#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Usage:  $ sync_extractions_TO_s3 j023507-040202"
    
    exit
fi

root=$1

# Run in root directory, like /Volumes/Pegasus/Grizli/Automatic/

# aws s3 sync --exclude "*" --include "${root}/Extractions/*GrismFLT*"  \
#                           --include "${root}/Extractions/*npy" \
#                           --include "${root}/Extractions/*cat.fits" \
#                           --include "${root}/Extractions/${root}*" \
#                           --follow-symlinks  ./ s3://aws-grivam/Pipeline/


echo "Sync:    `date`" > ${root}.log
aws s3 cp ${root}.log s3://aws-grivam/Pipeline/Log/Sync/

aws s3 sync --exclude "*" --include "*GrismFLT*"  \
                          --include "*npy" \
                          --include "*cat.fits" \
                          --include "${root}*" \
                          --follow-symlinks ./ s3://aws-grivam/Pipeline/${root}/Extractions


