#!/bin/bash
roots=`ls *footprint.fits | sed "s/_footprint.fits//"`
for root in $roots; do 
    for ext in RAW Prep; do 
        echo ${root}/${ext} `ls ${root}/${ext}/*flc.fits | wc`
    done
     echo ""
done

